name: Test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2
    - name: Cache gems
      uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-rubydeps-${{ hashFiles('Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-rubydeps-
    - name: Install gems
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Run Rubocop
      run: bundle exec rubocop --parallel
    - name: Run tests
      run: bundle exec rake test
